# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 65e2f27ed954e0266eec824f9802146db82fe6440a02d1b806c37dbec681dd541c9bfda8ab4303b8e3d0c631c7c80452364bf56a3e3eb60722b83cedd362c14c

test:
  secret_key_base: 456873b2e510ab53a0817d2eae6825a4b8aab2426c495995bc5f213c4c4f0b25ac3f1fe64914d259bcda0f278dcc16cf17c44d7c64e2d9db3d416141d85dd667

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
